// Test definitions. Do NOT edit this file!

#define CATCH_CONFIG_MAIN // defines main() automatically

#include <catch2/catch.hpp>

#include "../Alumno.hpp"

TEST_CASE("Ex1", "[Probando constructor por default]") {
    Alumno a;
    SECTION("Verificando sus atributos iniciales") {
        INFO("FUNCIONALIDAD ESPERADA: El constructor por default debe inicializar matrícula 'A000000', nombre 'RICARDO RAFAEL QUINTERO MEZA', edad 18 y carrera 'ITC'.");
        INFO("PROGRAMACIÓN: Clase Alumno con constructor: Alumno(); Getters esperados: std::string getMatricula(), std::string getNombre(), int getEdad(), std::string getCarrera(). Deben devolver los valores iniciales indicados.");
        INFO("SUGERENCIA DE PROGRAMACIÓN: Inicializa los atributos en el constructor, respeta camelCase y evita variables sin uso.");

        REQUIRE(a.getMatricula()=="A000000");
        REQUIRE(a.getNombre()=="RICARDO RAFAEL QUINTERO MEZA");
        REQUIRE(a.getEdad()==18);
        REQUIRE(a.getCarrera()=="ITC");
    }
}

TEST_CASE("Ex2", "[Probando constructor con parametros iniciales]") {
    Alumno a("A178940", "LUZ LOPEZ CISNEROS", 19, "IC");
    SECTION("Verificando sus atributos iniciales") {
        INFO("FUNCIONALIDAD ESPERADA: El constructor con parámetros debe asignar a los atributos exactamente los valores recibidos.");
        INFO("PROGRAMACIÓN: Constructor: Alumno(std::string, std::string, int, std::string). Para esta prueba los getters deben devolver 'A178940', 'LUZ LOPEZ CISNEROS', 19 y 'IC'.");
        INFO("SUGERENCIA DE PROGRAMACIÓN: Asigna cada parámetro a su atributo correspondiente (usa this-> cuando sea claro) y valida tipos y orden de parámetros.");

        REQUIRE(a.getMatricula()=="A178940");
        REQUIRE(a.getNombre()=="LUZ LOPEZ CISNEROS");
        REQUIRE(a.getEdad()==19);
        REQUIRE(a.getCarrera()=="IC");
    }
}

TEST_CASE("Ex3", "[Probando setters]") {
    Alumno a("A178940", "LUZ LOPEZ CISNEROS", 19, "IC");
    SECTION("Verificando cambios en los atributos") {
        INFO("FUNCIONALIDAD ESPERADA: Los setters deben actualizar correctamente cada atributo del objeto.");
        INFO("PROGRAMACIÓN: Métodos: void setMatricula(std::string), void setNombre(std::string), void setEdad(int), void setCarrera(std::string). Los getters deben reflejar los nuevos valores.");
        INFO("SUGERENCIA DE PROGRAMACIÓN: Dentro de cada setter asigna el parámetro al atributo correspondiente, evita lógica extra y respeta la notación camelCase.");

        a.setMatricula("A178936");
        a.setNombre("CAROLINA CASTRO HERRERA");
        a.setEdad(20);
        a.setCarrera("IMT");

        REQUIRE(a.getMatricula()=="A178936");
        REQUIRE(a.getNombre()=="CAROLINA CASTRO HERRERA");
        REQUIRE(a.getEdad()==20);
        REQUIRE(a.getCarrera()=="IMT");
    }
}

TEST_CASE("Ex4", "[Probando Imprimir alumno]") {
    Alumno a("A178940", "LUZ LOPEZ CISNEROS", 19, "IC");
    SECTION("Mostrando en consola los datos del alumno") {
        INFO("FUNCIONALIDAD ESPERADA: Debe imprimirse en consola la informacion del alumno en líneas separadas usando std::cout.");
        INFO("PROGRAMACIÓN: Método: void imprimeAlumno(); Formato sugerido: 'Matricula: ...', 'Nombre: ...', 'Edad: ...', 'Carrera: ...'.");
        INFO("SUGERENCIA DE PROGRAMACIÓN: Usa std::cout con fin de línea '\\n'; evita texto extra para que la salida sea predecible.");

        a.imprimeAlumno();

        REQUIRE(true);
    }
}

TEST_CASE("Ex5", "[Probando el cumpleaños del alumno]") {
    Alumno a("A178940", "LUZ LOPEZ CISNEROS", 19, "IC");
    a.cumpleAnios();
    SECTION("Festejando al alumno por su cumpleaños") {
        INFO("FUNCIONALIDAD ESPERADA: Al llamar cumpleAnios() la edad debe incrementarse exactamente en 1.");
        INFO("PROGRAMACIÓN: Método: void cumpleAnios(); Debe modificar el miembro 'edad' del objeto (por ejemplo, this->edad++).");
        INFO("SUGERENCIA DE PROGRAMACIÓN: Modifica directamente el atributo 'edad' sin crear variables temporales innecesarias.");
        
        std::cout << "Felicidades " << a.getNombre() << " por tu cumpleaños No. " 
        << a.getEdad() << " !\n";

        REQUIRE(a.getEdad()==20);
    }
}